"""Checks that transcript.py labels who wrote each user record, using the
same classifier as scan.sh. Prints one token per user record: kind, plus
the command name for commands."""
import json, os, sys, tempfile, shutil

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "lib"))
import transcript


def u(text, **kw):
    return json.dumps({"type": "user", "uuid": f"u{len(LINES)}", "message": {"role": "user", "content": text}, **kw})


LINES = []
for line in (
    lambda: u("<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>"),
    lambda: u("<local-command-caveat>Caveat: generated by local commands</local-command-caveat>", isMeta=True),
    lambda: u("<command-message>catchup</command-message><command-name>/catchup</command-name><command-args>at x.md</command-args>",
              origin={"kind": "human"}),
    lambda: u("Base directory for this skill: /skills/catchup", isMeta=True),
    lambda: u("fix the tab bug", origin={"kind": "human"}),
    lambda: u("<task-notification><summary>Agent \"seat\" finished</summary></task-notification>",
              origin={"kind": "task-notification"}),
    lambda: u("Stop hook feedback: goal not met", isMeta=True),
    lambda: u('Another Claude session sent a message: <teammate-message teammate_id="rev" summary="done">x</teammate-message>'),
    lambda: u("<local-command-stdout>Goal set</local-command-stdout>"),
):
    LINES.append(line())

root = tempfile.mkdtemp(prefix="turns-")
try:
    p = os.path.join(root, "s.jsonl")
    with open(p, "w") as fh:
        fh.write("\n".join(LINES) + "\n")
    recs = transcript.parse_transcript(p)["records"]
    out = []
    for r in recs:
        if r.get("role") != "user":
            continue
        k = r.get("turn") or "-"
        out.append(k + (":" + r["command"] if r.get("command") else ""))
    print(" ".join(out))
finally:
    shutil.rmtree(root, ignore_errors=True)
